name: link check

on:
  schedule:
    - cron: '0 6 * * *'  # 06:00 UTC = 03:00 GMT-3
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar requests
      run: pip install requests

    - name: Ejecutar verificación de links
      run: python scripts/check_url.py
